/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.pop.optimizer;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author 0x2
 */
public class CrewSettings extends javax.swing.JFrame {
    private CrewEdit edit = null;
    private ArrayList<Crew> team = new ArrayList<>();

    /**
     * Creates new form CrewSettings
     */
    public CrewSettings() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        
        for(int i=0; i<30; i++)
        {
            Crew c = new Crew();
            if(i<5)
                c.setName("Captain "+(i+1));
            else
                c.setName("Crew "+(i-4));
            
            team.add(c);
        }
        
        loadButtons();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        captain1 = new javax.swing.JButton();
        captain2 = new javax.swing.JButton();
        captain4 = new javax.swing.JButton();
        captain3 = new javax.swing.JButton();
        captain5 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        crew1 = new javax.swing.JButton();
        crew6 = new javax.swing.JButton();
        crew16 = new javax.swing.JButton();
        crew11 = new javax.swing.JButton();
        crew21 = new javax.swing.JButton();
        crew2 = new javax.swing.JButton();
        crew7 = new javax.swing.JButton();
        crew12 = new javax.swing.JButton();
        crew17 = new javax.swing.JButton();
        crew22 = new javax.swing.JButton();
        crew3 = new javax.swing.JButton();
        crew8 = new javax.swing.JButton();
        crew13 = new javax.swing.JButton();
        crew18 = new javax.swing.JButton();
        crew23 = new javax.swing.JButton();
        crew4 = new javax.swing.JButton();
        crew9 = new javax.swing.JButton();
        crew14 = new javax.swing.JButton();
        crew19 = new javax.swing.JButton();
        crew24 = new javax.swing.JButton();
        crew5 = new javax.swing.JButton();
        crew10 = new javax.swing.JButton();
        crew15 = new javax.swing.JButton();
        crew20 = new javax.swing.JButton();
        crew25 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setTitle("Crew Settings");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Captains");

        captain1.setText("Captain 1");
        captain1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editCrew(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                editCrew(evt);
            }
        });

        captain2.setText("Captain 2");
        captain2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editCrew(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                editCrew(evt);
            }
        });

        captain4.setText("Captain 4");
        captain4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editCrew(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                captain4MousePressed(evt);
            }
        });

        captain3.setText("Captain 3");
        captain3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editCrew(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                editCrew(evt);
            }
        });

        captain5.setText("Captain 5");
        captain5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editCrew(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                editCrew(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(captain4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(captain2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(captain3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(captain5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(captain1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(captain1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(captain2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(captain3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(captain4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(captain5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setText("Crew");

        crew1.setText("Crew 1");
        crew1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editCrew(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                editCrew(evt);
            }
        });

        crew6.setText("Crew 6");
        crew6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editCrew(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                editCrew(evt);
            }
        });

        crew16.setText("Crew 16");
        crew16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editCrew(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                editCrew(evt);
            }
        });

        crew11.setText("Crew 11");
        crew11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editCrew(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                editCrew(evt);
            }
        });

        crew21.setText("Crew 21");
        crew21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editCrew(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                editCrew(evt);
            }
        });

        crew2.setText("Crew 2");
        crew2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editCrew(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                editCrew(evt);
            }
        });

        crew7.setText("Crew 7");
        crew7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editCrew(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                editCrew(evt);
            }
        });

        crew12.setText("Crew 12");
        crew12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editCrew(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                editCrew(evt);
            }
        });

        crew17.setText("Crew 17");
        crew17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editCrew(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                editCrew(evt);
            }
        });

        crew22.setText("Crew 22");
        crew22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editCrew(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                editCrew(evt);
            }
        });

        crew3.setText("Crew 3");
        crew3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editCrew(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                editCrew(evt);
            }
        });

        crew8.setText("Crew 8");
        crew8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editCrew(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                editCrew(evt);
            }
        });

        crew13.setText("Crew 13");
        crew13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editCrew(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                editCrew(evt);
            }
        });

        crew18.setText("Crew 18");
        crew18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editCrew(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                editCrew(evt);
            }
        });

        crew23.setText("Crew 23");
        crew23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editCrew(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                editCrew(evt);
            }
        });

        crew4.setText("Crew 4");
        crew4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editCrew(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                editCrew(evt);
            }
        });

        crew9.setText("Crew 9");
        crew9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editCrew(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                editCrew(evt);
            }
        });

        crew14.setText("Crew 14");
        crew14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editCrew(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                editCrew(evt);
            }
        });

        crew19.setText("Crew 19");
        crew19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editCrew(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                editCrew(evt);
            }
        });

        crew24.setText("Crew 24");
        crew24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editCrew(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                editCrew(evt);
            }
        });

        crew5.setText("Crew 5");
        crew5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editCrew(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                editCrew(evt);
            }
        });

        crew10.setText("Crew 10");
        crew10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editCrew(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                editCrew(evt);
            }
        });

        crew15.setText("Crew 15");
        crew15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editCrew(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                editCrew(evt);
            }
        });

        crew20.setText("Crew 20");
        crew20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editCrew(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                editCrew(evt);
            }
        });

        crew25.setText("Crew 25");
        crew25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editCrew(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                editCrew(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(crew21, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(crew22, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(crew6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(crew7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(crew16, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(crew17, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(crew11, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(crew12, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(crew13, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(crew8, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(crew18, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(crew23, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(crew1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(crew2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(crew3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(crew24, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(crew25, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(crew4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(crew5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(crew9, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(crew10, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(crew14, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(crew15, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(crew19, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(crew20, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crew2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(crew1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(crew3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(crew4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(crew5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(crew10, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(crew7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(crew6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(crew8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(crew9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(crew11, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(crew12, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(crew13, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(crew14, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(8, 8, 8)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(crew16, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(crew17, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(crew18, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(crew19, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(crew20, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(crew15, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(crew24, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(crew23, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(crew21, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(crew22, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(crew25, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jButton2.setText("Close");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onCloseBt(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                onCloseBt(evt);
            }
        });

        jButton3.setText("Load");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onLoad(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                onLoad(evt);
            }
        });

        jButton4.setText("Save");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onSave(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                onSave(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editCrew(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editCrew
        JButton b = (JButton) evt.getSource();
        Crew c = team.get(button2Int(b));
        
        edit.setWindowTitle(c.getName(), b);
        
        edit.giveCrew(c);
        edit.receiveParent(this);
        edit.setVisible(true);
    }//GEN-LAST:event_editCrew

    private void onCloseBt(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onCloseBt
        this.setVisible(false);
    }//GEN-LAST:event_onCloseBt

    private void onSave(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onSave
        JFileChooser fc = new JFileChooser();
        if(fc.showSaveDialog(this) == javax.swing.JFileChooser.APPROVE_OPTION)
        {
            File fl = fc.getSelectedFile();
            try {
                ObjectOutputStream out = new ObjectOutputStream(new FileOutputStream(fl.getPath()+".clist"));
                out.writeObject(team);
                out.flush();
                out.close();
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this,ex.getLocalizedMessage(),"Save error",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_onSave

    private void onLoad(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onLoad
        FileFilter ft = new FileNameExtensionFilter("Crew List Files", "clist");
        JFileChooser fc = new JFileChooser();
        fc.addChoosableFileFilter(ft);
        
        if(fc.showOpenDialog(this) == javax.swing.JFileChooser.APPROVE_OPTION)
        {
            File fl = fc.getSelectedFile();
            try {
                ObjectInputStream in = new ObjectInputStream(new FileInputStream(fl));
                team = (ArrayList<Crew>) in.readObject();
                in.close();
                loadButtons();
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this,ex.getLocalizedMessage(),"Load error",JOptionPane.ERROR_MESSAGE);
            } catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(this,ex.getLocalizedMessage(),"Load error",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_onLoad

    private void captain4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_captain4MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_captain4MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrewSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrewSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrewSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrewSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrewSettings().setVisible(true);
            }
        });
    }
    
    public void setAOP(Boolean b)
    {
        this.setAlwaysOnTop(b);
    }
    
    public void setEditScreen(CrewEdit c)
    {
        edit = c;
    }
    
    public void updateCrew(Crew c, JButton sender)
    {
        setButtonText(c, sender);
        
        team.set(button2Int(sender), c);
    }
    
    public ArrayList<Crew> getCrew()
    {
        return team;
    }
    
    public void setTeam(ArrayList<Crew> t)
    {
        team = t;
        loadButtons();
    }
    
    private void setButtonText(Crew c, JButton sender)
    {
        String name = c.getName();
        if("".equals(c.getName()))
        {
            int id = button2Int(sender);
            if(id<5)
                name = "Captain "+(id+1);
            else
                name = "Crew "+(id-4);
        }
            
        if(c.isAvailable())
            sender.setText("<html><center>"+name+"<br />"+c.getStats()[0]+" / "+c.getStats()[1]+" / "+c.getStats()[2]+"</center></html>");
        else
            sender.setText("<html><center>"+name+"<br />"+"* At sea *"+"</center></html>");
    }
    
    private void loadButtons()
    {
        setButtonText(team.get(0), this.captain1);
        setButtonText(team.get(1), this.captain2);
        setButtonText(team.get(2), this.captain3);
        setButtonText(team.get(3), this.captain4);
        setButtonText(team.get(4), this.captain5);
        
        setButtonText(team.get(5), this.crew1);
        setButtonText(team.get(6), this.crew2);
        setButtonText(team.get(7), this.crew3);
        setButtonText(team.get(8), this.crew4);
        setButtonText(team.get(9), this.crew5);
        setButtonText(team.get(10), this.crew6);
        setButtonText(team.get(11), this.crew7);
        setButtonText(team.get(12), this.crew8);
        setButtonText(team.get(13), this.crew9);
        setButtonText(team.get(14), this.crew10);
        setButtonText(team.get(15), this.crew11);
        setButtonText(team.get(16), this.crew12);
        setButtonText(team.get(17), this.crew13);
        setButtonText(team.get(18), this.crew14);
        setButtonText(team.get(19), this.crew15);
        setButtonText(team.get(20), this.crew16);
        setButtonText(team.get(21), this.crew17);
        setButtonText(team.get(22), this.crew18);
        setButtonText(team.get(23), this.crew19);
        setButtonText(team.get(24), this.crew20);
        setButtonText(team.get(25), this.crew21);
        setButtonText(team.get(26), this.crew22);
        setButtonText(team.get(27), this.crew23);
        setButtonText(team.get(28), this.crew24);
        setButtonText(team.get(29), this.crew25);
    }
    
    private int button2Int(JButton sender)
    {
        int n=0;
        if(sender.equals(captain1))
            n = 0;
        if(sender.equals(captain2))
            n = 1;
        if(sender.equals(captain3))
            n = 2;
        if(sender.equals(captain4))
            n = 3;
        if(sender.equals(captain5))
            n = 4;
        if(sender.equals(crew1))
            n = 5;
        if(sender.equals(crew2))
            n = 6;
        if(sender.equals(crew3))
            n = 7;
        if(sender.equals(crew4))
            n = 8;
        if(sender.equals(crew5))
            n = 9;
        if(sender.equals(crew6))
            n = 10;
        if(sender.equals(crew7))
            n = 11;
        if(sender.equals(crew8))
            n = 12;
        if(sender.equals(crew9))
            n = 13;
        if(sender.equals(crew10))
            n = 14;
        if(sender.equals(crew11))
            n = 15;
        if(sender.equals(crew12))
            n = 16;
        if(sender.equals(crew13))
            n = 17;
        if(sender.equals(crew14))
            n = 18;
        if(sender.equals(crew15))
            n = 19;
        if(sender.equals(crew16))
            n = 20;
        if(sender.equals(crew17))
            n = 21;
        if(sender.equals(crew18))
            n = 22;
        if(sender.equals(crew19))
            n = 23;
        if(sender.equals(crew20))
            n = 24;
        if(sender.equals(crew21))
            n = 25;
        if(sender.equals(crew22))
            n = 26;
        if(sender.equals(crew23))
            n = 27;
        if(sender.equals(crew24))
            n = 28;
        if(sender.equals(crew25))
            n = 29;
        return n;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton captain1;
    private javax.swing.JButton captain2;
    private javax.swing.JButton captain3;
    private javax.swing.JButton captain4;
    private javax.swing.JButton captain5;
    private javax.swing.JButton crew1;
    private javax.swing.JButton crew10;
    private javax.swing.JButton crew11;
    private javax.swing.JButton crew12;
    private javax.swing.JButton crew13;
    private javax.swing.JButton crew14;
    private javax.swing.JButton crew15;
    private javax.swing.JButton crew16;
    private javax.swing.JButton crew17;
    private javax.swing.JButton crew18;
    private javax.swing.JButton crew19;
    private javax.swing.JButton crew2;
    private javax.swing.JButton crew20;
    private javax.swing.JButton crew21;
    private javax.swing.JButton crew22;
    private javax.swing.JButton crew23;
    private javax.swing.JButton crew24;
    private javax.swing.JButton crew25;
    private javax.swing.JButton crew3;
    private javax.swing.JButton crew4;
    private javax.swing.JButton crew5;
    private javax.swing.JButton crew6;
    private javax.swing.JButton crew7;
    private javax.swing.JButton crew8;
    private javax.swing.JButton crew9;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
