/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.pop.optimizer;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author 0x2
 */
public class ShipSettings extends javax.swing.JFrame {
    private ArrayList<String> decks = new ArrayList<>();
    private ArrayList<String> hulls = new ArrayList<>();
    private ArrayList<String> rams = new ArrayList<>();
    private String wright = "Dilapidated shipwright";
    private int[] indDecks = {};
    private int[] indHulls = {};
    private int[] indRams = {};
    private OptimizerInterface parent = null;
    
    /**
     * Creates new form ShipSettings
     */
    public ShipSettings() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        deckList = new javax.swing.JList();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        hullList = new javax.swing.JList();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        ramList = new javax.swing.JList();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        wrightList = new javax.swing.JList();
        jPanel3 = new javax.swing.JPanel();
        shipCheckBox = new java.awt.Checkbox();
        jLabel1 = new javax.swing.JLabel();
        sMorale = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        sCombat = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        sSeafaring = new javax.swing.JSpinner();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setTitle("Ship Settings");
        setResizable(false);

        jButton1.setText("Cancel");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onCancel(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                onCancel(evt);
            }
        });

        jButton2.setText("Ok");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onOk(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                onOk(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setText("Decks");

        deckList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Weathered Rigging", "Small Crate of Food", "Sturdy Rigging", "Large Crate of Food", "Single Cannon", "Entwined Rigging", "Small Crate of Riches", "Cannon x2", "Oxskin Rigging", "Large Crate of Riches", "Heavy Cannon x2", "Ornate Rigging", "Eastern Artefacts", "Cannon x3", "Whaleskin Rigging", "Eastern Treasures", "Cannon x4", "Dragonskin Rigging", "Eastern Relics", "Heavy Cannon x4", "Overwhelmingly Large Cannon x4", "Bladewing Rigging", "Fineglow Lanterns" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        deckList.setToolTipText("Press Ctrl + click to select multiple!");
        deckList.setEnabled(false);
        jScrollPane2.setViewportView(deckList);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setText("Hulls");

        hullList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Barnacled Hull", "Reinforced Hull", "Sleek Hull", "Battle Hull", "Golden Hull", "Hull of Tides", "Armoured Hull", "Hull of Storms", "War Hull", "Hull of Glory", "Storm Rider Hull", "Golden Katana Hull", "Blazing Lantern Hull", "Blackwater Hull", "Shimmering Azure Hull" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        hullList.setToolTipText("Press Ctrl + click to select multiple!");
        hullList.setEnabled(false);
        jScrollPane3.setViewportView(hullList);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3)
                .addContainerGap())
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setText("Rams / Figureheads");

        ramList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Weathered Ram", "Polished Figurehead", "Sturdy Ram", "Enchanted Figurehead", "Reinforced Ram", "Skeletal Figurehead", "Armoured Ram", "Ghostly Figurehead", "Battle Ram", "Intrepid Figurehead", "War Ram", "Inspiring Figurehead", "Spitfire Cannon", "Figurehead of the Spires", "Ram of the Bladewing" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        ramList.setToolTipText("Press Ctrl + click to select multiple!");
        ramList.setEnabled(false);
        jScrollPane5.setViewportView(ramList);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setText("Shipwright Building");

        wrightList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Dilapidated shipwright", "Refitted shipwright", "Renovated shipwright", "Nautical shipwright", "Warship shipwright", "Luxurious shipwright", "Sleek shipwright", "Ostentatious shipwright", "Battleship shipwright", "Maritime shipwright" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        wrightList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        wrightList.setToolTipText("Only one selection is possible");
        jScrollPane4.setViewportView(wrightList);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        shipCheckBox.setLabel("Search optimal ship settings too (72x slower), or use these ship stats: ");
        shipCheckBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                shipCheckBoxItemStateChanged(evt);
            }
        });

        jLabel1.setText("Morale:");

        sMorale.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(100)));

        jLabel2.setText("Combat:");

        sCombat.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(100)));

        jLabel7.setText("Seafaring:");

        sSeafaring.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(100)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(shipCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sMorale, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sCombat, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sSeafaring, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(sMorale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(sCombat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)
                        .addComponent(sSeafaring, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(shipCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton3.setText("Load");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onLoad(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                onLoad(evt);
            }
        });

        jButton4.setText("Save");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onSave(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                onSave(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onOk(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onOk
        loading();
        if(this.shipCheckBox.getState())
            parent.setSrchBt("<html><center>Search !<br />~ 72 minutes</center></html>");
        else
            parent.setSrchBt("<html><center>Search !<br />~ 1 minute</center></html>");
        this.setVisible(false);
    }//GEN-LAST:event_onOk

    private void onCancel(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onCancel
        this.setVisible(false);
        if(this.indDecks.length > 0)
            this.deckList.setSelectedIndices(indDecks);
        if(this.indHulls.length > 0)
            this.hullList.setSelectedIndices(indHulls);
        if(this.indRams.length > 0)
            this.ramList.setSelectedIndices(indRams);
        this.wrightList.setSelectedValue(wright, true);
    }//GEN-LAST:event_onCancel

    private void onSave(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onSave
        loading();
        
        Ship s = new Ship();
        s.setDeck(indDecks);
        s.setHull(indHulls);
        s.setRam(indRams);
        s.setWright(wright);
        s.setEnabled(this.shipCheckBox.getState());
        int[] stats = {(int) this.sMorale.getValue(), (int) this.sCombat.getValue(), (int) this.sSeafaring.getValue()};
        s.setDfltStats(stats);
        
        JFileChooser fc = new JFileChooser();
        if(fc.showSaveDialog(this) == javax.swing.JFileChooser.APPROVE_OPTION)
        {
            File fl = fc.getSelectedFile();
            try {
                ObjectOutputStream out = new ObjectOutputStream(new FileOutputStream(fl.getPath()+".ship"));
                out.writeObject(s);
                out.flush();
                out.close();
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this,ex.getLocalizedMessage(),"Save error",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_onSave

    private void onLoad(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onLoad
        FileFilter ft = new FileNameExtensionFilter("Ship Files", "ship");
        JFileChooser fc = new JFileChooser();
        fc.addChoosableFileFilter(ft);
        
        if(fc.showOpenDialog(this) == javax.swing.JFileChooser.APPROVE_OPTION)
        {
            File fl = fc.getSelectedFile();
            try {
                ObjectInputStream in = new ObjectInputStream(new FileInputStream(fl));
                
                Ship s = (Ship) in.readObject();
                indDecks = s.getDeck();
                indHulls = s.getHull();
                indRams = s.getRam();
                wright = s.getWright();
                this.sMorale.setValue((int) s.getDfltStats()[0]);
                this.sCombat.setValue((int) s.getDfltStats()[1]);
                this.sSeafaring.setValue((int) s.getDfltStats()[2]);
                
                this.deckList.setSelectedIndices(indDecks);
                this.hullList.setSelectedIndices(indHulls);
                this.ramList.setSelectedIndices(indRams);
                this.wrightList.setSelectedValue(wright, true);
                this.shipCheckBox.setState(s.getEnabled());
                this.shipCheckBoxItemStateChanged(null);
                
                in.close();
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this,ex.getLocalizedMessage(),"Load error",JOptionPane.ERROR_MESSAGE);
            } catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(this,ex.getLocalizedMessage(),"Load error",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_onLoad

    private void shipCheckBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_shipCheckBoxItemStateChanged
        this.deckList.setEnabled(this.shipCheckBox.getState());
        this.hullList.setEnabled(this.shipCheckBox.getState());
        this.ramList.setEnabled(this.shipCheckBox.getState());
        this.sMorale.setEnabled(!this.shipCheckBox.getState());
        this.sCombat.setEnabled(!this.shipCheckBox.getState());
        this.sSeafaring.setEnabled(!this.shipCheckBox.getState());
    }//GEN-LAST:event_shipCheckBoxItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShipSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShipSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShipSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShipSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShipSettings().setVisible(true);
            }
        });
    }
    
    public void setAOP(Boolean b)
    {
        this.setAlwaysOnTop(b);
    }
    
    public Ship getShip()
    {
        loading();
        Ship s = new Ship();
        s.setDeck(indDecks);
        s.setHull(indHulls);
        s.setRam(indRams);
        s.setWright(wright);
        s.setEnabled(this.shipCheckBox.getState());
        int[] stats = {(int) this.sMorale.getValue(), (int) this.sCombat.getValue(), (int) this.sSeafaring.getValue()};
        s.setDfltStats(stats);
        return s;
    }
    
    public void setShip(Ship s)
    {
        this.deckList.setSelectedIndices(s.getDeck());
        this.hullList.setSelectedIndices(s.getHull());
        this.ramList.setSelectedIndices(s.getRam());
        this.wrightList.setSelectedValue(s.getWright(), true);
        this.shipCheckBox.setState(s.getEnabled());
        loading();
        this.sMorale.setValue((int) s.getDfltStats()[0]);
        this.sCombat.setValue((int) s.getDfltStats()[1]);
        this.sSeafaring.setValue((int) s.getDfltStats()[2]);
        this.shipCheckBoxItemStateChanged(null);
    }
    
    private void loading()
    {
        if(!this.deckList.isSelectionEmpty())
        {
            decks = (ArrayList) this.deckList.getSelectedValuesList();
            indDecks = this.deckList.getSelectedIndices();
        }
        if(!this.hullList.isSelectionEmpty())
        {
            hulls = (ArrayList) this.hullList.getSelectedValuesList();
            indHulls = this.hullList.getSelectedIndices();
        }
        if(!this.ramList.isSelectionEmpty())
        {
            rams = (ArrayList) this.ramList.getSelectedValuesList();
            indRams = this.ramList.getSelectedIndices();
        }
        if(!this.wrightList.isSelectionEmpty())
            wright = (String) this.wrightList.getSelectedValue();
    }
    
    public void setParent(OptimizerInterface oi)
    {
        parent = oi;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList deckList;
    private javax.swing.JList hullList;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JList ramList;
    private javax.swing.JSpinner sCombat;
    private javax.swing.JSpinner sMorale;
    private javax.swing.JSpinner sSeafaring;
    private java.awt.Checkbox shipCheckBox;
    private javax.swing.JList wrightList;
    // End of variables declaration//GEN-END:variables
}
